#include "cli_arg_required.hpp"

namespace wowee {
namespace editor {
namespace cli {

const char* const kArgRequired[] = {
    "--data", "--info", "--info-batches", "--info-textures", "--info-doodads",
    "--info-attachments", "--info-particles", "--info-sequences",
    "--info-bones", "--export-bones-dot",
    "--list-zone-meshes", "--list-zone-audio", "--list-zone-textures",
    "--list-project-meshes", "--list-project-audio",
    "--list-project-textures",
    "--info-zone-models-total", "--info-project-models-total",
    "--list-zone-meshes-detail", "--list-project-meshes-detail", "--info-mesh",
    "--info-mesh-storage-budget", "--info-mesh-stats",
    "--info-wob", "--info-wob-stats", "--info-woc", "--info-wot",
    "--info-wol", "--info-wol-at", "--validate-wol", "--gen-light",
    "--gen-light-cave", "--gen-light-dungeon", "--gen-light-night",
    "--export-wol-json", "--import-wol-json",
    "--info-wow", "--validate-wow",
    "--gen-weather-temperate", "--gen-weather-arctic",
    "--gen-weather-desert", "--gen-weather-stormy",
    "--gen-zone-atmosphere",
    "--info-creatures", "--info-objects", "--info-quests",
    "--info-extract", "--info-extract-tree", "--info-extract-budget",
    "--list-missing-sidecars",
    "--info-png", "--info-jsondbc", "--info-blp", "--info-pack-budget",
    "--info-pack-tree",
    "--info-m2", "--info-wmo", "--info-adt",
    "--info-zone", "--info-zone-overview", "--info-project-overview",
    "--copy-project", "--info-wcp", "--list-wcp",
    "--list-creatures", "--list-objects", "--list-quests",
    "--list-quest-objectives", "--list-quest-rewards",
    "--info-creature", "--info-quest", "--info-object",
    "--info-quest-graph-stats",
    "--info-creatures-by-faction", "--info-creatures-by-level",
    "--info-objects-by-path", "--info-objects-by-type",
    "--info-quests-by-level", "--info-quests-by-xp",
    "--unpack-wcp", "--pack-wcp",
    "--validate", "--validate-wom", "--validate-wob", "--validate-woc",
    "--validate-whm", "--validate-all", "--validate-project",
    "--validate-project-open-only", "--audit-project", "--bench-audit-project",
    "--bench-validate-project", "--bench-bake-project",
    "--bench-migrate-data-tree", "--list-data-tree-largest",
    "--export-data-tree-md", "--gen-texture", "--gen-mesh", "--gen-mesh-textured",
    "--add-texture-to-mesh", "--add-texture-to-zone",
    "--gen-mesh-stairs", "--gen-mesh-grid", "--gen-mesh-disc",
    "--gen-mesh-tube", "--gen-mesh-capsule", "--gen-mesh-arch",
    "--gen-mesh-pyramid", "--gen-mesh-fence", "--gen-mesh-tree",
    "--gen-mesh-rock", "--gen-mesh-pillar", "--gen-mesh-bridge",
    "--gen-mesh-tower", "--gen-mesh-house", "--gen-mesh-fountain",
    "--gen-mesh-statue", "--gen-mesh-altar", "--gen-mesh-portal",
    "--gen-mesh-archway", "--gen-mesh-barrel", "--gen-mesh-chest",
    "--gen-mesh-anvil", "--gen-mesh-mushroom", "--gen-mesh-cart",
    "--gen-mesh-banner", "--gen-mesh-grave", "--gen-mesh-bench",
    "--gen-mesh-shrine", "--gen-mesh-totem", "--gen-mesh-cage",
    "--gen-mesh-throne", "--gen-mesh-coffin", "--gen-mesh-bookshelf",
    "--gen-mesh-tent", "--gen-mesh-firepit", "--gen-mesh-woodpile",
    "--gen-mesh-canopy", "--gen-mesh-haystack", "--gen-mesh-dock",
    "--gen-mesh-pergola", "--gen-mesh-chimney", "--gen-mesh-bedroll",
    "--gen-mesh-workbench", "--gen-mesh-crate-stack",
    "--gen-mesh-watchpost", "--gen-mesh-water-trough",
    "--gen-mesh-training-dummy", "--gen-mesh-hitching-post",
    "--gen-mesh-outhouse", "--gen-mesh-forge",
    "--gen-mesh-archery-target", "--gen-mesh-gravel-pile",
    "--gen-mesh-stone-bench", "--gen-mesh-mine-cart",
    "--gen-mesh-hitching-rail", "--gen-mesh-pillar-row",
    "--gen-mesh-statue-base", "--gen-mesh-bird-bath",
    "--gen-mesh-planter-box", "--gen-mesh-urn", "--gen-mesh-candle",
    "--gen-mesh-lantern", "--gen-mesh-chalice",
    "--gen-mesh-standing-torch", "--gen-mesh-scroll-case",
    "--gen-mesh-stove",
    "--gen-camp-pack", "--gen-blacksmith-pack", "--gen-village-pack",
    "--gen-temple-pack", "--gen-graveyard-pack",
    "--gen-garden-pack", "--gen-dock-pack", "--gen-tavern-pack",
    "--gen-mining-pack", "--gen-arena-pack",
    "--gen-mesh-table", "--gen-mesh-lamppost", "--gen-mesh-bed",
    "--gen-mesh-ladder", "--gen-mesh-well", "--gen-mesh-signpost",
    "--gen-mesh-mailbox", "--gen-mesh-tombstone", "--gen-mesh-crate",
    "--gen-mesh-stool", "--gen-mesh-cauldron", "--gen-mesh-gate",
    "--gen-mesh-beehive", "--gen-mesh-weathervane",
    "--gen-mesh-scarecrow", "--gen-mesh-sundial",
    "--gen-mesh-podium", "--gen-mesh-brazier", "--gen-mesh-archway-double",
    "--gen-texture-gradient",
    "--gen-mesh-from-heightmap", "--export-mesh-heightmap",
    "--displace-mesh",
    "--scale-mesh", "--translate-mesh", "--strip-mesh",
    "--gen-texture-noise", "--gen-texture-noise-color", "--rotate-mesh",
    "--center-mesh", "--flip-mesh-normals", "--mirror-mesh",
    "--smooth-mesh-normals",
    "--merge-meshes",
    "--gen-texture-radial", "--gen-texture-stripes", "--gen-texture-dots",
    "--gen-texture-rings", "--gen-texture-checker", "--gen-texture-brick",
    "--gen-texture-wood", "--gen-texture-grass", "--gen-texture-fabric",
    "--gen-texture-cobble", "--gen-texture-marble", "--gen-texture-metal",
    "--gen-texture-leather", "--gen-texture-sand", "--gen-texture-snow",
    "--gen-texture-lava", "--gen-texture-tile", "--gen-texture-bark",
    "--gen-texture-clouds", "--gen-texture-stars", "--gen-texture-vines",
    "--gen-texture-mosaic", "--gen-texture-rust", "--gen-texture-circuit",
    "--gen-texture-coral", "--gen-texture-flame", "--gen-texture-tartan",
    "--gen-texture-argyle", "--gen-texture-herringbone",
    "--gen-texture-scales", "--gen-texture-stained-glass",
    "--gen-texture-shingles", "--gen-texture-frost",
    "--gen-texture-parquet", "--gen-texture-bubbles",
    "--gen-texture-spider-web", "--gen-texture-gingham",
    "--gen-texture-lattice", "--gen-texture-honeycomb",
    "--gen-texture-cracked", "--gen-texture-runes",
    "--gen-texture-leopard", "--gen-texture-zebra",
    "--gen-texture-knit", "--gen-texture-chainmail",
    "--gen-texture-planks", "--gen-texture-corrugated",
    "--gen-texture-rope", "--gen-texture-caustics",
    "--gen-texture-starburst", "--gen-texture-studs",
    "--gen-texture-moss", "--gen-texture-woodgrain",
    "--gen-texture-carbon", "--gen-texture-pinstripe",
    "--gen-texture-camo", "--gen-texture-snake-skin",
    "--gen-texture-mesh-screen", "--gen-texture-bamboo",
    "--gen-texture-blueprint", "--gen-texture-rust-streaks",
    "--gen-texture-plaid", "--gen-texture-diamond-grid",
    "--gen-texture-houndstooth", "--gen-texture-chevron",
    "--gen-texture-dunes", "--gen-texture-swirl",
    "--gen-texture-ironbark", "--gen-texture-mold",
    "--gen-texture-embroidery", "--gen-texture-lightbeam",
    "--gen-texture-dewdrops", "--gen-texture-pinwheel",
    "--gen-texture-scratched-metal", "--gen-texture-crackle",
    "--gen-texture-star", "--gen-texture-halftone",
    "--gen-texture-bayer",
    "--validate-glb", "--info-glb", "--info-glb-tree", "--info-glb-bytes",
    "--validate-jsondbc", "--check-glb-bounds", "--validate-stl",
    "--validate-png", "--validate-blp",
    "--zone-summary", "--info-zone-tree", "--info-project-tree",
    "--info-zone-bytes", "--info-project-bytes",
    "--info-zone-extents", "--info-project-extents",
    "--info-zone-water", "--info-project-water",
    "--info-zone-density", "--info-project-density",
    "--export-zone-summary-md", "--export-quest-graph",
    "--export-zone-csv", "--export-zone-html", "--export-project-html",
    "--export-project-md", "--export-zone-checksum", "--export-project-checksum",
    "--validate-project-checksum",
    "--scaffold-zone", "--mvp-zone", "--add-tile", "--remove-tile", "--list-tiles",
    "--for-each-zone", "--for-each-tile", "--zone-stats", "--info-tilemap",
    "--list-zone-deps", "--list-project-orphans", "--remove-project-orphans",
    "--check-zone-refs", "--check-zone-content",
    "--check-project-content", "--check-project-refs",
    "--export-zone-deps-md", "--export-zone-spawn-png",
    "--add-creature", "--add-object", "--add-quest", "--add-item",
    "--random-populate-zone", "--random-populate-items",
    "--info-zone-audio", "--snap-zone-to-ground", "--audit-zone-spawns",
    "--info-project-audio", "--snap-project-to-ground",
    "--audit-project-spawns", "--list-zone-spawns", "--list-project-spawns",
    "--gen-random-zone", "--gen-random-project", "--gen-zone-texture-pack",
    "--gen-zone-mesh-pack", "--gen-zone-starter-pack",
    "--gen-project-starter-pack", "--gen-audio-tone",
    "--gen-audio-noise", "--gen-audio-sweep", "--gen-zone-audio-pack",
    "--info-zone-summary", "--info-project-summary",
    "--info-zone-deps", "--info-project-deps",
    "--gen-zone-readme", "--gen-project-readme",
    "--validate-zone-pack", "--validate-project-packs", "--info-spawn",
    "--diff-zone-spawns",
    "--list-items", "--info-item", "--set-item", "--export-zone-items-md",
    "--export-project-items-md", "--export-project-items-csv",
    "--add-quest-objective", "--add-quest-reward-item", "--set-quest-reward",
    "--remove-quest-objective", "--clone-quest", "--clone-creature",
    "--clone-item", "--validate-items", "--validate-project-items",
    "--info-project-items",
    "--clone-object",
    "--remove-creature", "--remove-object", "--remove-quest", "--remove-item",
    "--copy-zone-items",
    "--copy-zone", "--rename-zone", "--remove-zone",
    "--clear-zone-content", "--strip-zone", "--strip-project",
    "--repair-zone", "--repair-project",
    "--gen-makefile", "--gen-project-makefile",
    "--build-woc", "--regen-collision", "--fix-zone",
    "--export-png", "--export-obj", "--import-obj",
    "--export-wob-obj", "--import-wob-obj",
    "--export-woc-obj", "--export-whm-obj",
    "--export-glb", "--export-wob-glb", "--export-whm-glb",
    "--export-stl", "--import-stl",
    "--bake-zone-glb", "--bake-zone-stl", "--bake-zone-obj",
    "--bake-project-obj", "--bake-project-stl", "--bake-project-glb",
    "--bake-wom-collision", "--bake-wob-collision", "--bake-zone-collision",
    "--audit-watertight", "--audit-watertight-wob",
    "--convert-m2", "--convert-m2-batch",
    "--convert-wmo", "--convert-wmo-batch",
    "--convert-dbc-json", "--convert-dbc-batch", "--convert-json-dbc",
    "--convert-blp-png", "--convert-blp-batch",
    "--migrate-wom", "--migrate-zone", "--migrate-project",
    "--migrate-data-tree", "--info-data-tree", "--strip-data-tree",
    "--audit-data-tree",
    "--migrate-jsondbc",
};

const std::size_t kArgRequiredSize =
    sizeof(kArgRequired) / sizeof(kArgRequired[0]);

} // namespace cli
} // namespace editor
} // namespace wowee
